name: video-max

services:
  streamx-db:
    image: postgres:15-alpine
    container_name: streamx-db
    networks:
      - streamx_net
    ports:
      - '${DB_POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  sonarqube:
    image: sonarqube:9.9.0-community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - streamx-db
    networks:
      - streamx_net
    ports:
      - "9003:9000"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - streamx_net
    ports:
      - '15432:80'
    depends_on:
      - streamx-db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    networks:
      - streamx_net
    ports:
      - '9000:9000'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  uptime-kuma:
    image: louislam/uptime-kuma:2.4.0
    container_name: uptime-kuma
    networks:
      - streamx_net
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks:
      - streamx_net
    ports:
      - '8083:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    networks:
      - streamx_net
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - streamx_net
    restart: always
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: rabbitmq
    hostname: ${RABBITMQ_HOST}
    networks:
      - streamx_net
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    networks:
      - streamx_net
    ports:
      - '9002:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${BUCKET_NAME}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
  uptime-kuma:

networks:
  streamx_net:
    driver: bridge
